### PR TITLE
README Improvements

### PR DESCRIPTION
**Pull request by montymxb**
Some general suggestions for fixes regarding language and such.

### CODE REVIEW

**Comment by premithk** [comment]
Thanks a lot :)

**Comment by montymxb** [comment]
Np :+1:

**Comment by montymxb** [comment]
@premithk one more little thing I just noticed. `email@.gmail.com` has a little `.` before `gmail.com`. You can probably remove that as well, seems to be a typo I missed.

**Comment by premithk** [comment]
@montymxb yeah, have changed that :)

**Pull request merged**
